global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'node-exporter'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9100

  - job_name: 'node-exporter-host'
    static_configs:
      - targets: ['192.168.123.1:9100']

  - job_name: 'node-exporter-jenkins'
    static_configs:
    - targets: ['223.130.156.49:9100']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['db_mysql-master:9104']
 
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['db_redis:9121']

  - job_name: 'dockerswarm'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        regex: (.+)
        action: keep
        target_label: job

      - source_labels: [__address__]
        regex: .*:0
        action: drop

  - job_name: 'jshop'
    scrape_interval: 2s
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep

      - source_labels: [__meta_dockerswarm_service_label_jshop]
        regex: (.+)
        action: keep
        target_label: was

      - source_labels: [__meta_dockerswarm_network_name]
        regex: jshop
        action: keep

      - target_label: __metrics_path__
        replacement: /actuator/prometheus

      - source_labels: [__address__]
        target_label: __address__
        regex: "(.+):([0-9]+)"
        replacement: "$1:8080"
