{
 "title": "JVM (Micrometer)",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "live_instances",
    "label": "Instances",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\"},id)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "인스턴스 정보",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "jvm_info{instance=~\"$live_instances\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  { "title": "모든 인스턴스 퍼포먼스", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "JVM Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_threads_states_threads{instance=~\"$live_instances\"}) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(jvm_threads_states_threads{instance=~\"$live_instances\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "4xx Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(    \n    http_server_requests_seconds_count{\n        application=\"$application\",         \n        instance=~\"$live_instances\",\n        status =~ \"4..\"\n    }    \n) by (method, uri, error, status, instance) > 0",
     "legendFormat": "{{instance}} - {{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "5xx Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(    \n    http_server_requests_seconds_count{\n        application=\"$application\", \n        error != \"none\", \n        instance=~\"$live_instances\"\n    }    \n) by (method, uri, error, status, instance) > 0",
     "legendFormat": "{{instance}} - {{method}} {{uri}} - error : {{error}} "
    },
    {
     "expr": "sum(\n    http_server_requests_seconds_count{\n        application=\"$application\", \n        status =~ \"5..\", \n        instance=~\"$live_instances\"\n    }\n)by (method, uri, error, status, instance) > 0",
     "legendFormat": "{{instance}} - {{method}} {{uri}} {{status}} - error : {{error}} "
    }
   ]
  },
  {
   "title": "요청 응답 시간 (s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n    irate(http_server_requests_seconds_sum{\n        application=\"$application\",     \n        uri !~\"/actuator/prometheus|UNKNOWN\", \n        instance=~\"$live_instances\"\n    }[1m]\n) /\nirate(\n    http_server_requests_seconds_count{\n        application=\"$application\",     \n        uri !~\"/actuator/prometheus|UNKNOWN\", \n        instance=~\"$live_instances\"\n    }[1m]\n)) by (status, method, uri, instance, error) > 0",
     "legendFormat": "{{instance}} - {{method}} {{uri}} {{status}}  | error - {{error}}"
    },
    {
     "expr": "avg(\n    irate(http_server_requests_seconds_sum{\n        application=\"$application\",     \n        uri = \"UNKNOWN\", \n        instance=~\"$live_instances\",\n        status=\"200\",\n        error=\"none\"\n    }[1m]\n) /\nirate(\n    http_server_requests_seconds_count{\n        application=\"$application\",     \n        uri = \"UNKNOWN\", \n        instance=~\"$live_instances\",\n        status=\"200\",\n        error=\"none\"\n    }[1m]\n)) by (status, method, uri, instance, error) > 0",
     "legendFormat": "{{instance}} - {{method}} /api/login {{status}}  | error - {{error}}"
    }
   ]
  },
  {
   "title": "초당 응답 수 (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(\n    irate(http_server_requests_seconds_count{\n        application=\"$application\", \n        error = \"none\", \n        uri !~ \"/actuator/prometheus|UNKNOWN\", \n        instance=~\"$live_instances\",\n        status =~\"2..\"}[1m]\n    )\n) by (method, uri, error, status, instance) > 0",
     "legendFormat": "{{instance}} - {{method}} {{uri}} {{status}}"
    },
    {
     "expr": "avg(\n  label_replace(\n    irate(http_server_requests_seconds_count{\n      application=\"$application\", \n      error = \"none\", \n      uri = \"UNKNOWN\", \n      status =~\"2..\",\n      instance=~\"$live_instances\"\n    }[1m]), \n    \"uri\",\n    \"/api/login\",\n    \"uri\",\n    \"UNKNOWN\"\n  )\n) by (method, uri, error, status, instance) > 0",
     "legendFormat": "{{instance}} - {{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(jvm_threads_states_threads{instance=\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "인스턴스 퍼포먼스",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "4xx Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(    \n    http_server_requests_seconds_count{\n        application=\"$application\", \n        status =~ \"4..\", \n        instance=\"$instance\"\n    }    \n)by (method, uri, error, status) > 0",
     "legendFormat": "{{method}} {{uri}} {{exception}} {{status}}"
    }
   ]
  },
  {
   "title": "5xx Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(    \n    http_server_requests_seconds_count{\n        application=\"$application\", \n        status =~ \"5..\", \n        instance=\"$instance\"\n    }    \n)by (method, uri, error, status) > 0",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    },
    {
     "expr": "sum(    \n    http_server_requests_seconds_count{\n        application=\"$application\", \n        error != \"none\", \n        instance=\"$instance\"\n    }    \n) by (method, uri, error, status) > 0",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "요청 응답 시간 (s)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "avg(\n    irate(http_server_requests_seconds_sum{\n        application=\"$application\",     \n        uri !~\"/actuator/prometheus|UNKNOWN\", \n        instance=\"$instance\"\n    }[1m]\n) /\nirate(\n    http_server_requests_seconds_count{\n        application=\"$application\",     \n        uri !~\"/actuator/prometheus|UNKNOWN\", \n        instance=\"$instance\"\n    }[1m]\n)) by (status, method, uri, instance, error) > 0",
     "legendFormat": "{{method}} {{uri}} {{status}}  | error - {{error}}"
    },
    {
     "expr": "avg(\n    irate(http_server_requests_seconds_sum{\n        application=\"$application\",     \n        uri = \"UNKNOWN\", \n        instance=\"$instance\",\n        status=\"200\",\n        error=\"none\"\n    }[1m]\n) /\nirate(\n    http_server_requests_seconds_count{\n        application=\"$application\",     \n        uri = \"UNKNOWN\", \n        instance=~\"$instance\",\n        status=\"200\",\n        error=\"none\"\n    }[1m]\n)) by (status, method, uri, instance, error) > 0",
     "legendFormat": "{{method}} /api/login {{status}}  | error - {{error}}"
    },
    {
     "expr": "avg(\n    irate(http_server_requests_seconds_sum{\n        application=\"$application\",     \n        uri = \"UNKNOWN\", \n        instance=\"$instance\",\n        status !~ \"2..\",\n        error=\"none\"\n    }[1m]\n) /\nirate(\n    http_server_requests_seconds_count{\n        application=\"$application\",     \n        uri = \"UNKNOWN\", \n        instance=\"$instance\",\n        status !~\"2..\",\n        error=\"none\"\n    }[1m]\n)) by (status, method, uri, instance, error) > 0",
     "legendFormat": "{{method}} {{uri}} {{status}}  | error - {{error}}"
    }
   ]
  },
  {
   "title": "초당 응답 개수 (RPS)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "avg(\n    irate(http_server_requests_seconds_count{\n        application=\"$application\", \n        error = \"none\", \n        uri !~ \"/actuator/prometheus|UNKNOWN\", \n        instance=\"$instance\",\n        status =~\"2..\"}[1m]\n    )\n) by (method, uri, error, status) > 0",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    },
    {
     "expr": "avg(\n  label_replace(\n    irate(http_server_requests_seconds_count{\n      application=\"$application\", \n      error = \"none\", \n      uri = \"UNKNOWN\", \n      status =~\"2..\",\n      instance=~\"$instance\"\n    }[1m]), \n    \"uri\",\n    \"/api/login\",\n    \"uri\",\n    \"UNKNOWN\"\n  )\n) by (method, uri, error, status)",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[15m])",
     "legendFormat": "process-15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "GC Pressure",
   "type": "timeseries",
   "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])) by (application, instance) / on(application, instance) system_cpu_count",
     "legendFormat": "CPU time spent on GC"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_files_open_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
     "repeat": "jvm_memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 90 },
     "repeat": "jvm_memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pause Durations",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])/irate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_gc_overhead{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{application=\"$application\",instance=\"$instance\"}[1m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_buffer_pool",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 73 },
     "repeat": "jvm_buffer_pool",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "capacity"
      },
      {
       "expr": "jvm_buffer_count_buffers{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
       "legendFormat": "buffers"
      }
     ]
    }
   ]
  }
 ]
}