{
 "title": "MySQL Dashboard",
 "description": "The Dashboard display Visualization Data from MySQL Exporter configured with Prometheus Database",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,10m,30m,1h,6h,12h" },
   {
    "name": "host",
    "label": "Server",
    "query": {
     "query": "label_values(mysql_up, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall MySQL Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Buffer Pool Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=\"$host\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_flush_log_at_trx_commit",
     "legendFormat": "Log Tx Commit"
    },
    {
     "expr": "mysql_global_variables_innodb_log_files_in_group",
     "legendFormat": "Log files Group"
    }
   ]
  },
  {
   "title": "DB Node Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"192.168.123.202:9100\"}[1m])))",
     "legendFormat": "Cpu"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"192.168.123.202:9100\"} / node_memory_MemTotal_bytes{instance=\"192.168.123.202:9100\"})) * 100",
     "legendFormat": "Memory"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"192.168.123.202:9100\", device=\"vda\"} [1m]) * 100",
     "legendFormat": "Disk I/O"
    },
    {
     "expr": "node_load1{instance=\"192.168.123.202:9100\"}",
     "legendFormat": "Cpu Load"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "MySQL Server Uptime - The time elapsed since the last restart of the MySQL server.",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Query/Sec",
   "type": "stat",
   "description": "Queries Processed By Server Per Second\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(irate(mysql_global_status_queries{instance=\"$host\"}[5m]), \"instance\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "targets": [
    { "expr": "mysql_version_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Clinets Connections",
   "type": "timeseries",
   "description": "Max Clients Connections - Max Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections. \nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\nConnections is the number of connection attempts to the MySQL server.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Connections"
    },
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"$host\"}",
     "legendFormat": "Max Used Connections"
    },
    {
     "expr": "mysql_global_variables_max_connections{instance=\"$host\"}",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Activity",
   "type": "timeseries",
   "description": "Description: MySQL Active Threads - Threads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{instance=\"$host\"}",
     "legendFormat": "Peak Threads Connected"
    },
    {
     "expr": "mysql_global_status_threads_running{instance=\"$host\"}",
     "legendFormat": "Peak Threads Running"
    }
   ]
  },
  { "title": "테이블 캐시 / 버퍼풀", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "초당 버퍼풀 I/O ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}[1m])",
     "legendFormat": "Read From Buffer Pool"
    }
   ]
  },
  {
   "title": "버퍼풀 데이터 바이트 수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_buffer_pool_bytes_data{instance=\"$host\"}",
     "legendFormat": "Buffer Pool Bytes"
    }
   ]
  },
  {
   "title": "초당 디스크 I/O 횟수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_reads{instance=\"$host\"}[1m])",
     "legendFormat": "Buffer Pool Pages"
    }
   ]
  },
  {
   "title": "디스크 I/O 바이트",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_data_read{instance=\"$host\"}",
     "legendFormat": "Buffer Pool Pages"
    }
   ]
  },
  {
   "title": "초당 핸들러 캐시 히트",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "hit/s" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[1m])",
     "legendFormat": "cache_hits"
    }
   ]
  },
  {
   "title": "버퍼풀 데이터 페이지 수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "mysql_global_status_buffer_pool_pages{state=\"data\", instance=\"$host\"}",
     "legendFormat": "Buffer Pool Pages"
    }
   ]
  },
  {
   "title": "Processes, Commands and Handlers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction Per Seconds",
     "type": "timeseries",
     "description": "초당 명령 증가율",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "topk(5, irate(mysql_global_status_commands_total{instance=\"$host\"}[10m]))",
       "legendFormat": "{{ command }}"
      }
     ]
    },
    {
     "title": "10분간 명령 호출 증가량",
     "type": "timeseries",
     "description": "10분동안 호출된 명령의 합",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, increase(mysql_global_status_commands_total{instance=\"$host\"}[10m]))",
       "legendFormat": "{{ command }}"
      }
     ]
    },
    {
     "title": "MySQL Handlers",
     "type": "timeseries",
     "description": "Handler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\nThis is in fact the layer between the Storage Engine and MySQL.\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(mysql_global_status_handlers_total{instance=\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "MySQL Transaction Handlers",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(mysql_global_status_handlers_total{instance=\"$host\", handler=~\"commit|rollback|savepoint.*|prepare\"}[5m])",
       "legendFormat": "{{ handler }}"
      }
     ]
    }
   ]
  },
  { "title": "Memory Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "MySQL Internal Memory Overview",
   "type": "timeseries",
   "description": "***System Memory***: Total Memory for the system.\\\n***InnoDB Buffer Pool Data***: InnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.\\\n***TokuDB Cache Size***: Similar in function to the InnoDB Buffer Pool,  TokuDB will allocate 50% of the installed RAM for its own cache.\\\n***Key Buffer Size***: Index blocks for MYISAM tables are buffered and are shared by all threads. key_buffer_size is the size of the buffer used for index blocks.\\\n***Adaptive Hash Index Size***: When InnoDB notices that some index values are being accessed very frequently, it builds a hash index for them in memory on top of B-Tree indexes.\\\n ***Query Cache Size***: The query cache stores the text of a SELECT statement together with the corresponding result that was sent to the client. The query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time.\\\n***InnoDB Dictionary Size***: The data dictionary is InnoDB ‘s internal catalog of tables. InnoDB stores the data dictionary on disk, and loads entries into memory while the server is running.\\\n***InnoDB Log Buffer Size***: The MySQL InnoDB log buffer allows transactions to run without having to write the log to disk before the transactions commit.\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_page_size{instance=\"$host\"} * on (instance) mysql_global_status_buffer_pool_pages{instance=\"$host\",state=\"data\"}",
     "legendFormat": "InnoDB Buffer Pool Data"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$host\"}",
     "legendFormat": "System Memory"
    },
    {
     "expr": "mysql_global_variables_innodb_log_buffer_size{instance=\"$host\"}",
     "legendFormat": "InnoDB Log Buffer Size"
    },
    {
     "expr": "mysql_global_variables_innodb_additional_mem_pool_size{instance=\"$host\"}",
     "legendFormat": "InnoDB Additional Memory Pool Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_dictionary{instance=\"$host\"}",
     "legendFormat": "InnoDB Dictionary Size"
    },
    {
     "expr": "mysql_global_variables_key_buffer_size{instance=\"$host\"}",
     "legendFormat": "Key Buffer Size"
    },
    {
     "expr": "mysql_global_status_innodb_mem_adaptive_hash{instance=\"$host\"}",
     "legendFormat": "Adaptive Hash Index Size"
    }
   ]
  },
  { "title": "MySQL Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "MySQL Network Traffic",
   "type": "timeseries",
   "description": "MySQL Network Traffic\nMySQL Network Traffic - Here we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received{instance=\"$host\"}[5m])",
     "legendFormat": "Inbound"
    },
    {
     "expr": "irate(mysql_global_status_bytes_sent{instance=\"$host\"}[5m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "MySQL Network Usage Hourly",
   "type": "timeseries",
   "description": "MySQL Network Usage Hourly\nMySQL Network Usage Hourly - Here we can see how much network traffic is generated by MySQL per hour. You can use the bar graph to compare data sent by MySQL and data received by MySQL.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received{instance=\"$host\"}[1m])",
     "legendFormat": "Received"
    },
    {
     "expr": "irate(mysql_global_status_bytes_sent{instance=\"$host\"}[1m])",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}